### ISSUE TITLE
unity 运行显示空白

### ISSUE THREAD

**Issue by ascdqz** [TastSong/CrazyCar#25]
嗨 Tast
我按照你的视频教程，用unity打开了crazycarclient，版本也是特意用了和你一样的（虽然后面少了个c1）然后用安卓打开，但是看到的界面和你的教程并不一样。你的打开是login界面，我的是untitled，如下图所示。是什么原因呢？
感谢！
![image](https://github.com/TastSong/CrazyCar/assets/65437325/b4fc2c43-aad6-4e9e-81fd-a49a7466a13f)

**Comment by DukeHouse** [comment]
> 嗨 Tast 我按照你的视频教程，用unity打开了crazycarclient，版本也是特意用了和你一样的（虽然后面少了个c1）然后用安卓打开，但是看到的界面和你的教程并不一样。你的打开是login界面，我的是untitled，如下图所示。是什么原因呢？ 感谢！ ![image](https://private-user-images.githubusercontent.com/65437325/266461609-b4fc2c43-aad6-4e9e-81fd-a49a7466a13f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjQwNjQsIm5iZiI6MTcxNjk2Mzc2NCwicGF0aCI6Ii82NTQzNzMyNS8yNjY0NjE2MDktYjRmYzJjNDMtYWFkNi00ZTllLTgxZmQtYTQ5YTc0NjZhMTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA2MjI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMjg1MGI2OTkxODA5YjlkNjZlNGIwYzgyYzk4M2I5YTdmZDZjZDcwNTFmMzRkMzcwMTk1NGUzNzJiODMxMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uMIcVuBzrVO28fNZh-UinUTIT6TWeaSjyWvAyaElHic)

我也是这个问题，请问后来解决了吗？

**Comment by TastSong** [comment]
你应该需要一些Unity的基础培训，你需要在Project面板搜索Login,如下图，然后双击开：













在 2024-05-29 14:23:37，"DukeHouse" ***@***.***> 写道：

嗨 Tast 我按照你的视频教程，用unity打开了crazycarclient，版本也是特意用了和你一样的（虽然后面少了个c1）然后用安卓打开，但是看到的界面和你的教程并不一样。你的打开是login界面，我的是untitled，如下图所示。是什么原因呢？ 感谢！

我也是这个问题，请问后来解决了吗？
