### ISSUE TITLE
多重预编译错误，带了2个Json包了。多了一个Json包。

### ISSUE THREAD

**Issue by jyunfan2015** [TastSong/CrazyCar#6]
unity 编辑器提示

Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included on the current platform. Only one assembly with the same name is allowed per platform. (Assets/Plugins/Newtonsoft Json/Runtime/Newtonsoft.Json.dll)

多重预编译错误，带了2个Json包了。多了一个Json包。

Unity 2021.3.X创建一个新项目的时候，package manager自带了一个JSON包了，开发者可以不用再次引入json包了。

删除Plugins下的json包，就可以运行了。

![CrazyCar01](https://user-images.githubusercontent.com/12136292/184058426-9376f8f2-bb47-4289-be77-c9d03d495aca.jpg)

**Comment by jyunfan2015** [comment]
对了，我用的项目版本是ed234e6a0bfab9690b63b576171624d3ca8aab9a

**Comment by jyunfan2015** [comment]
我用的版本是ed234e6a0bfab9690b63b576171624d3ca8aab9a

**Comment by TastSong** [comment]
项目现在使用的版本是2021.3.1f，此版本新建项目并不会自带Newtonsoft Json
